import {accountPrefix} from './Function';

export const PAGE_ID = {
    LOGIN: 0,
    SIGN_UP: 1,
    PATIENT_PURCHASABLE_INSURANCE_LIST: 2,
    PATIENT_PURCHASABLE_INSURANCE_DETAIL: 3,
    PATIENT_PURCHASE_INSURANCE_WARRANTY: 4,
    PATIENT_PERSONAL_CENTER: 5,
    PATIENT_PURCHASED_INSURANCE_LIST: 6,
    PATIENT_PURCHASED_INSURANCE_DETAIL: 7,
    PATIENT_DIRECT_PAYMENT_LIST: 8,
    PATIENT_DIRECT_PAYMENT_DETAIL: 9,
};

export const ROUTE = {
    [PAGE_ID.LOGIN]: accountPrefix('/login'),
    [PAGE_ID.SIGN_UP]: accountPrefix('/signUp'),
};